name: Push container images to GitHub Packages

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  push-container-image:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - 17

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT_FOR_GITHUB_PACKAGES }}

      - name: Build container images
        run: docker build -t "ghcr.io/kota2and3kan/debug-postgresql:${{ matrix.version }}" ./postgresql${{ matrix.version }}/

      - name: Check container images
        run: docker image ls

      - name: Push container images
        run: docker push ghcr.io/kota2and3kan/debug-postgresql:${{ matrix.version }}
